name: Update M3U

on:
  schedule:
    - cron: '0 * * * *' # Ejecutar cada hora
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update M3U file
      run: |
        echo "#EXTM3U" > IPTV.m3u
        echo "#EXTINF:-1, Channel 1" >> IPTV.m3u
        echo "http://example.com/stream1" >> IPTV.m3u
        echo "#EXTINF:-1, Channel 2" >> IPTV.m3u
        echo "http://example.com/stream2" >> IPTV.m3u

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add IPTV.m3u
        git commit -m "Update IPTV.m3u"
        git push
